# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name:deafult

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: mvn clean install
  displayName: 'Build with maven '
- script: java -jar target/Ansible1-1.0-SNAPSHOT.jar
  displayName: 'Running jar'
